#cflags-y	+= -os

#hotplugs

obj-$(CONFIG_BLU_PLUG)        += blu_plug.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_hotplug.o
obj-$(CONFIG_MSM_HOTPLUG)     += msm_hotplug.o
obj-$(CONFIG_AUTOSMP)         += autosmp.o
